#Autogenerated file (by config.py) dont edit!
import sys,os
sys.path.append(os.environ['BRIDGE_ENTRY_PATH'])
exec("import "+os.environ['BRIDGE_ENTRY_NAME']+" as main_module")
main_loop=main_module.main_loop
kill=main_module.kill
def reload():
  import imp
  imp.reload(main_module)
  if hasattr(main_module,'reload'):
    main_module.reload()
  print('entrypoint reloaded')
